import math

file = "sineLookup.c"

# Number of entries per period
period = 120

# zero-peak amplitude
ampMax = 2**15-1

sineVals = [int(ampMax*math.sin( 2*math.pi*n/period )) for n in range(period)]


h = open(file, 'w')

h.write("/* Autogenerated by generateSineTable.py */\n")
h.write("#include <stdint.h>\n\n")

h.write("/* Sine lookup table with period {} and zero-peak amplitude {} */\n".format(period, ampMax))
h.write("const int16_t sineLookup[] = {")
h.write(", ".join("{}".format(x) for x in sineVals))
h.write("};")